### PR TITLE
Migrate ticketing reports to Python

### PR DESCRIPTION
**Pull request by chrean**
PowerShell is just... Meh.
Plus the script does not appear to work properly, hence the intention to refactor using a proper language.

### CODE REVIEW

**Comment by lwhitelock** [comment]
You have included your public API keys in the PR. Please go and reset them inside Ninja asap and remove them from the code. Also this script is designed to be executed by Ninja and python is not a supported language. What problems did you hit?

**Comment by chrean** [comment]
Thank you @lwhitelock , that was indeed quite an oversight on my end. Luckily the API key has been revoked and the NinjaOne instance appears to not have been compromised.
As for the script, I guess it's just me not being 100% confident with Ninja; how is the script supposed to be used? I thought it had to be executed from a PowerShell on any Windows client, or? In my case it is returning no data, so I wanted to debug it a little bit to figure out what I was doing wrong.

**Comment by lwhitelock** [comment]
So the script is designed to just be able to be scheduled from inside NinjaOne and make use of role secure fields to keep your API credentials safe. Have a check of the getting started guide which talks about how to configure a machine to run the scripts https://docs.mspp.io/ninjaone/getting-started
If its returning no data, the most likely thing is that its missing the columns that need to be added to the all tickets board. Have a check here in the guide for that script to see what fields are needed https://docs.mspp.io/ninjaone/enhanced-ticketing-reports#ninjaone-settings

**Comment by chrean** [comment]
Thank you @lwhitelock , I will give it a try and let you know. Wasn't aware of the above, I guess we'll need some more in-depth Ninja training. :)

**Comment by chrean** [comment]
Hello again @lwhitelock , with some help from NinjaOne tech support I have managed to make the script run (although, there was an issue with NuGet I also needed to fix).
Now the script runs properly but no tickets are found. I was wondering e.g. how the variable `$Tickets` is meant to be populated here:

https://github.com/lwhitelock/NinjaOneAutomation/blob/ff1700780a8d658a7ddbf2a82db695c3495a87bd/DocumentationScripts/NinjaOne-Ticketing-Report.ps1#L460

Feels like I am still missing some pieces... Thanks for any help you may be able to provide.

**Pull request closed without merging**
